import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {HeroUIProvider} from "@heroui/system";
import {ReactNode} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "react 19",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: ReactNode;}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <HeroUIProvider>
      <div className={'w-5xl mx-auto my-10 bg-gray-100 p-4 rounded-md'}>
        {children}
      </div>
    </HeroUIProvider>
    </body>
    </html>
  );
}
